
/**
Constructor
Do not call Function in Constructor.
*/
class mansTab()
{
	super();

	//TODO:edit here

}
extends AView;


function mansTab*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function mansTab*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function mansTab*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
