
/**
Constructor
Do not call Function in Constructor.
*/
class onePlusTab()
{
	super();

	//TODO:edit here

}
extends AView;


function onePlusTab*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function onePlusTab*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function onePlusTab*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
