
/**
Constructor
Do not call Function in Constructor.
*/
class shopingLiveTab()
{
	super();

	//TODO:edit here

}
extends AView;


function shopingLiveTab*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function shopingLiveTab*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function shopingLiveTab*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
