
/**
Constructor
Do not call Function in Constructor.
*/
class shoppingLiveTab()
{
	super();

	//TODO:edit here

}
extends AView;


function shoppingLiveTab*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function shoppingLiveTab*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function shoppingLiveTab*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
