
/**
Constructor
Do not call Function in Constructor.
*/
class shopingTab()
{
	super();

	//TODO:edit here

}
extends AView;


function shopingTab*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function shopingTab*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function shopingTab*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
