
/**
Constructor
Do not call Function in Constructor.
*/
class shoppingTab()
{
	super();

	//TODO:edit here

}
extends AView;


function shoppingTab*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function shoppingTab*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function shoppingTab*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
